### ISSUE TITLE
herbart

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1069]

**Comment by i-davis** [comment]
s1: *Grapes of Wrath* first published 1939. I'm hesitant to put this down as notAfter 1941: since Herbart was once Gide's lover, it seems possible Sylvia would've lent to her after the war? No mention of her, either as "Herbart" or as "van Rysselberghe," in Fitch. Sylvia mentions her in a letter from 1959, but only as coming to a show & "causerie-party" afterward (280).

**Comment by elspethgreen** [comment]
There's a VERY faded year at the top corner--looks like it might be "194-something? I suppose you could just leave it at "notBefore" without the "notAfter," as that will still signal to the computer folks that the date is estimated.

**Comment by i-davis** [comment]
Ok: I might do notBefore 1939 // notAfter 1949? I agree that year looks like 194* –– at the very least, it's not 195* or 196*. I'm guessing it's after the war since there's no subscription info, which seems like Sylvia's standard practice after the official years - just recordings of lendings but w/o charging anyone anything for borrowings. To be really safe, I think notAfter 1961 might be the only guaranteed thing (Sylvia was at Les Déserts for the summer of 62, I think; Fitch 414); but that seems overboard, & it does look like 194*.
