### ISSUE TITLE
Deletions

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mapping-expatriate-paris#12]
I have deleted two names in the personography: James Mark Baldwin (I could only find a card for his wife) and Thorton Baker (ditto: only Mrs. Baker has a card as far as I can see).

**Comment by cwulfman** [comment]
See comment to #11 . I think we should put them back, in that &lt;listPerson xml:id="others"&gt; element.

**Comment by jkotin** [comment]
But should we include people in the personography who weren't members of the lending library?

**Comment by cwulfman** [comment]
That's why I put them in the "others" list. It's a complication, though: it depends on whether or not you want to represent relationships like marriage in your data.

I don't think we should assume lending-library membership in the personography just because we notice them. (Was Beach a member of the library?) A person was a member of the lending library if they bought a subscription:

```xml
<person>
...
   <event type="S-and-Co-subscriber" from="1924-07-01" to="1925-07-01">
      <p>If you want, you can provide a prose description.</p>
    </event>
</person>
```
Being explicit like this has several advantages: It acknowledges that "membership in the lending library" is an inference based on observable data; it combines that acknowledgment with an encoding of evidence, always good in itself but also good for us because it enriches our database, making it possible for us to analyze patterns of subscription; and it makes our data more universally useful and sharable.

I've been assuming you were planning to encode these subscription events -- that's one of the main reasons to use this whole personography apparatus. Let's figure out a protocol (i.e., what type to give to these events -- "S-and-Co-subscriber" is a bit clumsy -- and so forth).

**Comment by jkotin** [comment]
I agree that we eventually want to incorporate membership data in the personography, but I have not been doing that yet.

When we talk tomorrow, let's discuss how best to do that.  Don't we have to wait for Harriet to be done before we have a clear sense of this information?

JK

**Comment by cwulfman** [comment]
I’ve been wondering about that: has Harriet even begun?

On Nov 3, 2015, at 17:02, jkotin <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree that we eventually want to incorporate membership data in the personography, but I have not been doing that yet.

When we talk tomorrow, let's discuss how best to do that. Don't we have to wait for Harriet to be done before we have a clear sense of this information?

JK
