### ISSUE TITLE
dennis

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1546]

**Comment by i-davis** [comment]
on s6 Dennis bought a book strap - haven't seen anyone else buy one before. have wondered what sort of side items S&co might've sold. anyone else seen any other book straps or other, uh, accessories?

**Comment by i-davis** [comment]
s1 is 1900s

**Comment by i-davis** [comment]
s1: *Europe Since the War* pub 1935

**Comment by i-davis** [comment]
s1 & s2 are Mrs. Frederic Dennis (#denn.ho) & all the rest seem to be Mary Cable Dennis (#denn.ma)

**Comment by i-davis** [comment]
So: re Mrs. (Frederic) Holly Beach Dennis. There's nothing about Holly in the logbooks (I've searched for Dennis, Frederic Dennis, Holly); I'm wondering how much Sylvia would've ever made Holly pay for a subscription anyway (tho there is a record of some payment at the top of s1). There's no mention in Fitch of Holly Beach visiting Paris after 1935, which this card must from after that, if *Europe Since the War* was borrowed. I've been searching & can't find records of a trip by Holly, not even in Sylvia's letters, after 1935; in fact, Sylvia was visiting Princeton & Altadena, & there saw Holly herself in 35-36. 

I'm guessing that Holly wouldn't've been reading *Europe Since the War* after 1939, when it might've started to feel obsolete for a reader like Holly (by which I mean she doesn't seem to've been doing historical work). So we're talking sometime in between 35-39?

The card notes postal charges, & one of the books borrowed is called *Mont St Michel & Chartres,* so it seems likely Holly was traveling in France (not in Italy, where she worked for the Red Cross in I think 21-22).

**Comment by i-davis** [comment]
(& the address/addresses are in France, except maybe for what might've been in Hartlepool, England)

& Sylvia took *Europe Since the War* & the *Mont St Michel & Chartres* book to Holly, it looks like, so Sylvia must've taken a trip to see Holly where she was.

Fitch 347 notes that in the summer of 1934 "Sylvia learned that Holly and Fred, who had claimed they were going to London for a writing assignment, had adopted and eleven-month-old English baby boy." So maybe Holly & Fred stuck around in England & France in 34-35? There's no mention in Fitch of Holly visiting Sylvia or Sylvia Holly in France after 1936.

**Comment by i-davis** [comment]
Fitch 347 also notes that Sylvia was reading *The Life of Trotsky* & *John Strachey's Coming Struggle for Power* in the summer of 34 & was more & more worried by german & italian fascists around that time, so maybe that interest translated to her taking Holly *Europe Since the War*?

**Comment by i-davis** [comment]
8 september 1935 was a sunday; but I think I can picture Sylvia going into the shop on a sunday to grab a book for Holly?

**Comment by i-davis** [comment]
I'm going to leave this & come back to it: I'm hoping that because it's Holly we can find some record, but I feel I'm running out of ideas.

**Comment by elspethgreen** [comment]
Hey Ian--would you mind making a final call on this and submitting a pull request?  It's fine if you can't work it out!

**Comment by i-davis** [comment]
Hi - sorry, totally, done! Thought I'd fixed this. I just now notBefored 1935 // notAftered 1938, though I remember being fairly convinced it's 35. Remaining problem: this card file still has two people merged in it.
