### ISSUE TITLE
Nationality 2

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mapping-expatriate-paris#18]
I'm trying to think about the best way to tag nationality. Eventually it will be important to know the nationality of the community that used the bookstore.  How many were American expatriates?  Yet nationality is a tricky thing—as the TEI guidelines make clear. What should we put for Walter Benjamin's nationality, for example?  One option would be to note y/n American.  But then we lose a lot of potentially interesting data.

**Comment by cwulfman** [comment]
How about:

```xml
<nationality to="1935-07-15" key="DE">German</nationality>
```

**Comment by jkotin** [comment]
Are the dates necessary?

The initial reason for my concern: it seems odd to call WB a German -- he was a German Jew.

But there are other tricky identifications: Ayala Bentovim was born in Jerusalem and became an Israeli citizen and then a dual citizen with Canada.  Seems odd to list her as Israeli -- but also odd to list her as "British Mandate for Palestine" or whatever.

But tough cases make bad law -- I'll stick with the program.

JK

**Comment by cwulfman** [comment]
Identification is interpretation. The date I supplied is not arbitrary (though it is wrong: I mistyped; it should be 1935-09-15) -- that is the date when the Reich Citizenship Law stripped German Jews of their citizenship. So under one, reasonable interpretation of nationality, Benjamin was German until the Nazis disenfranchised him. To say Benjamin can't be both German and Jewish sounds disturbingly complicit with the Nuremberg Laws, at least to me, though I'm quite sure that isn't what you meant.

Why not
```xml
<person>
     <faith>Jewish</faith>
      <nationality to="1935-09-15" key="DE">
        <note>Benjamin was born in Germany and was, under German law, a citizen of Germany
                      until the Reich Citizenship Law went into effect on September 15, 1934</note>
       </nationality>
</person>
```

(Though the connotation of the TEI element name &lt;faith&gt; is problematic and may be offensive to some.)

Identification is so toxic right now (see prior discussion of encoding gender) that I feel compelled to say, explicitly and publicly, that I have no "program" for you to stick with. This is your project, and I have simply suggested that the TEI schema is a useful tool for encoding the data you want to study. I believe there are ways of being sensitive to issues of identity while still gathering useful data, but perhaps we should be asking whether, like gender, this is data we actually want to use. So we come back to your original question: perhaps, if our only concern is to note who is American, we should only supply a nationality tag for those persons to whom we think that identification applies and omit it otherwise.
