### ISSUE TITLE
Reynal - questioning dates b/c cards out of order

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mapping-expatriate-paris#326]
I put 1900 for S3 because I wasn't sure what year it was. Unless it's supposed to follow S4, in which case it's 1938.

**Comment by i-davis** [comment]
On s3 Reynal renews the subscription halfway through the card on 26 november 1937. That doesn't guarantee that the first half of the card (8 april - 28 september) is from 1937 as well; however, Reynal checks out *Nightwood* on 27 may; *Nightwood* was published in october of 36. So that guarantees it's 1937.

**Comment by i-davis** [comment]
Order (1931-1940):
s1,
s2,
s3,
s4
