### ISSUE TITLE
fournerey

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#843]

**Comment by i-davis** [comment]
Fournerey (#four) in the personography, borrows just one helpful book on s1 (Vogue's Book of Etiquette), & then after returning the book on april 27th, rather unmannerlily stops borrowing or moves to a different (not extant) card. (WorldCat records the earliest Book of Etiquette as being pub 1923, but I'm not sure that's the first time it was published.) Another Fournerey is recorded as subscribing on 28 april 1920. I'm guessing they're the same Fournerey, since the one on the card is noted as being from Lycée Louis-le-Grand, & this'd match up with the "Prof" designation for the bunny in the logbook. Possible he returned the book on the 27th, & then came back the next day to subscribe for real & was given a different card for some reason? But I don't really know. I'm hesitant to do notBefore/notAfter for the entire spread of the library, or from 1923 on. Will keep thinking on this.

**Comment by i-davis** [comment]
Ok ok I give up: will do 1919 - 1941.
