### ISSUE TITLE
brullc

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#952]

**Comment by i-davis** [comment]
Colette Brull-Ulmann was born in 1920; can't really see her taking out a subscription until she was maybe 15-18? She lived on avenue du Général Maistre, which was named that in 1934, so it must be post-1934. She's Mlle Brull on the card, but she married Jacques Ulmann in 1943, so that doesn't help.


(<a href="http://www.v2asp.paris.fr/commun/v2asp/v2/nomenclature_voies/Voieactu/4037.nom.htm">naming of avenue</a>)

**Comment by i-davis** [comment]
Will keep working on this; there're lots of articles about her (she helped save some jewish children as an intern at Hôpital Rothschild during the war, between 41 & 43), so I'm hopeful I can find something more, maybe about when she moved to avenue du Général Maistre or started studying in Paris or something.
